### ISSUE TITLE
Usage description in README

### ISSUE THREAD

**Issue by rivera-ernesto** [peterthomashorn/macosfileproviderexample#2]
Could you please add some details about the current status, and more important, the usage of the demo app please?

What to run? Where to look for in the Finder for the file provider?

**Comment by peterthomashorn** [comment]
I extended the README. Please note that it is not intended to be a demo file provider but only the minimum necessary effort to get a file provider extension running for debugging (which does not work with the plain project template as supplied by Xcode).

**Comment by m-emelchenkov** [comment]
Peter, could you tell current status of this technology in Big Sur and especially Monterey? I am looking for seamless selective sync solution between a NAS and PC, I like its concept (by the way, same concept in Windows called 'cloud files API'). However:
- Apps like ChronoSync or GoodSync uses own UI for selective sync (and of course you can't oversee whole file system in Finder and system-wide if using selective sync this way).
- Resilio Connect seamless integrates with Windows but failed to sync my files. Test over. On macOS they use FUSE, its storage is not compatible with VMs and have other serious drawbacks.
- Strongsync client by Expandrive developer simply don't work, and he also ignores mails, and other people also mention this. So, "dead" product.
- Native Windows Offline Files. An abandoned technology with serious performance drawbacks due to its implementation.

Technically, we have multiple different apps to do selective sync task. But, in fact, no working apps which supports seamless selective sync on any of platforms at all.

**Comment by peterthomashorn** [comment]
The file provider framework is only a low-level API to integrate a storage service into the user interface and file system of the operating system (only Apple platform) and not an app as all those you listed. It does not synchronize anything by itself. That is the task of an app one can develop on top of that framework to integrate whatever is desired into Finder. Comparing the file provider framework with ready-to-use solutions like Nextcloud is a kind of comparing apples and oranges. As far as I understand you, the file provider framework is not what you are looking for.

By the way: Nextcloud works fine for me and people I know across platforms since years. I agree that the client feels a little bit alien due to its cross platform technology underneath (Qt, if I recall correctly). I would not call it even remotely amateur, though.

**Comment by m-emelchenkov** [comment]
Well, I am a developer with more than 20 years of experience and of course I understand the difference between an API and an app. I mean, nobody (properly) implemented sync software using this new API. Do you know samples? I suppose, if published this example there, you are the person who may know it better than anybody else.

**Comment by peterthomashorn** [comment]
Ok, if it is about solutions built on top of this framework I only know iCloud itself so far. A developer of Expandrive answered me once on StackOverflow apparently knowing more about this topic as he works on [Strongsync](https://www.expandrive.com/strongsync/). As far as I know, Strongsync is built on top of the file provider framework. I would like to adopt the file provider framework in the product I am currently working on to replace the current approach in the future. However that is a business decision and it depends on the progress and results another team has achieved which implements it for iOS. We are not fully convinced of the framework. There are issues with the integration into the iOS Files app beyond our control, in example search and the restrictions imposed by the sandboxed extension necessary for integration. I am not involved yet as I work on the macOS client. So far, I have been only trying to get a development environment started at all with this demo project. At that time there was neither a macOS project template for the file provider extension nor any documentation or hint on how that works except some API definitions. This has changed, though. [A whole session from this year's developer conference is published now, too](https://developer.apple.com/videos/play/wwdc2021/10182/). I am sorry, I did not get further than this yet.

**Comment by m-emelchenkov** [comment]
Thank you very much! I read somewhere that Apple provides much more info and support to their large partners than to regular developers, so their premium partners already implemented this feature. Yes, Apple's iCloud itself, and also Microsoft's OneDrive. Today I digging more and more info and found that OneDrive can be installed on SharePoint server, so you'll get on-premise OneDrive experience. I.e. buy HP MicroServer, install there Windows Server + SharePoint with OneDrive role, and it will fully replace home /small office NAS system. Because you'll get seamless file sharing experience in Windows, in macOS and a delta sync for all files as a bonus (especially useful on metered or slow connections, or just for huge files like mine, i.e. VM images). The only drawback is pricing. I suppose, it's the only product nowadays supporting modern syncing frameworks.
